version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - /deploy.sh
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  discard-paths: yes
  base-directory: 'dist'
  files:
    - '**/*'
