version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Nothing to do in the pre_build phase..."
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - aws cloudformation deploy --stack-name sevolabs-web --template-file ./cloudformation.template.yml
      - npm run build
      - aws s3 sync ./dist s3://sevolabs.com
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  discard-paths: yes
  base-directory: 'dist'
  files:
    - '**/*'
