
AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template

Resources:
  SevolabscomBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: 'sevolabs.com'
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
      VersioningConfiguration:
        Status: Enabled

  SevolabscomBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    DependsOn: SevolabscomBucket
    Properties:
      Bucket: !Ref SevolabscomBucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref SevolabscomBucket
                - /*
            Principal: '*'

  SevoLabsWebRecord:
    Type: AWS::Route53::RecordSet
    DependsOn: SevolabscomBucket
    Properties:
      Name: 'sevolabs.com'
      Type: A
      AliasTarget: 
        DNSName: 's3-website-eu-west-1.amazonaws.com'
        # EvaluateTargetHealth: False
        HostedZoneId: 'Z1BKCTXD74EZPE'
      HostedZoneName: 'sevolabs.com.'
      SetIdentifier: 'website'
      Region: 'eu-west-1'

  # SevolabsOriginAccessIdentity:
  #   Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  #   Properties: 
  #     CloudFrontOriginAccessIdentityConfig: 
  #       CloudFrontOriginAccessIdentityConfig

  SevolabsCloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: 
          - sevolabs.com
        DefaultRootObject: index.html
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: s3-sevolabs.com
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
        Origins:
          - DomainName: sevolabs.com.s3.amazonaws.com
            Id: s3-sevolabs.com
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: https-only
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:eu-west-1:403117364727:certificate/33772a3c-ed2d-4131-a065-f6b593bcb67e
          SslSupportMethod: sni-only
        IPV6Enabled: true
